# Generated by Django 4.2.1 on 2023-07-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('frontendapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=500, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('Zip', models.CharField(blank=True, max_length=100, null=True)),
                ('Mail', models.EmailField(blank=True, max_length=100, null=True)),
                ('Num', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
